# **Introdução à biblioteca NumPy**

**O que é o NumPy?**

NumPy é o pacote fundamental para computação científica em Python. É uma biblioteca que provê uma série de rotinas em alta velocidade com arrays multidimensionais, dentre as quais estão inclusas operações matemáticas, lógicas, estatísticas e muito mais.

**Importando o NumPy**



In [ ]:
import numpy as np

# **Por que prefere-se o NumPy às listas?**


# **Velocidade de execução**

Operações com arrays são mais rápidas utilizando o NumPy do que se fossem feito com as listas de Python. Isso se deve a:


*   Implementação da biblioteca é feita utilizando uma linguagem de programação mais rápida que Python, a linguagem C.
*   Alocação do array na memória é realizada de forma contígua no NumPy, diferentemente do que ocorre com as listas.



**NumPy x Listas: Comparando os tempos de execução da soma de todos os elementos de um vetor**

In [ ]:
import time

In [ ]:
inicio = time.time()

lista = list(range(100000000)) # cem milhões

print(f"Somatorio da lista: {sum(lista)}")
print(f"Tempo de execução: {(time.time() - inicio):.2f} segundos")

Somatorio da lista: 4999999950000000
Tempo de execução: 4.99 segundos


In [ ]:
inicio = time.time()

array_numpy = np.arange(100000000) # cem milhões

print(f"Somatorio do array numpy: {array_numpy.sum()}")
print(f"Tempo de execução: {(time.time() - inicio):.2f} segundos")

Somatorio do array numpy: 4999999950000000
Tempo de execução: 0.41 segundos


# **Vetorização**

**Considere as seguintes operações feitas com listas em Python**

In [ ]:
a = [1,2,3]
b = [4,5,6]
c = [7,8,9,10]
print(f" a = {a}")
print(f" b = {b}")
print(f" c = {c}")
print()

duas_vezes_a = []
for i in a:
  duas_vezes_a.append(2*i)
print(f" 2*a = {duas_vezes_a}")

sum = []
for i, j in zip(a, b):
  sum.append(i+j)
print(f"a + b = {sum}")

c_modificado = []
for i in c:
  if c.index(i) == 1 or c.index(i) == 2:
    c_modificado.append(0)
  else:
    c_modificado.append(i)
print(f"c modificado = {c_modificado}")

 a = [1, 2, 3]
 b = [4, 5, 6]
 c = [7, 8, 9, 10]

 2*a = [2, 4, 6]
a + b = [5, 7, 9]
c modificado = [7, 0, 0, 10]


**Agora, veja como elas ficam mais fáceis quando trabalhamos com o NumPy:**

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9,10])
print(f" a = {a}")
print(f" b = {b}")
print(f" c = {c}")
print()

duas_vezes_a = 2*a
print(f" 2*a = {duas_vezes_a}")

sum = a+b
print(f"a + b = {sum}")

c_modificado = np.copy(c)
c_modificado[1:3] = 0
print(f"c modificado = {c_modificado}")

 a = [1 2 3]
 b = [4 5 6]
 c = [ 7  8  9 10]

 2*a = [2 4 6]
a + b = [5 7 9]
c modificado = [ 7  0  0 10]


A vetorização do código com o NumPy traz dois grandes benefícios:


*   Código mais simples de ler e escrever
*   Remoção de loops torna o código mais eficiente



Agora, vamos olhar com mais cuidado para a vetorização nos seguintes casos:

In [ ]:
a = np.array([1,2,3])

duas_vezes_a = 2*a
print(f" 2*a = {duas_vezes_a}")
print()

dois_mais_a = 2+a
print(f" 2+a = {dois_mais_a}")
print()

 2*a = [2 4 6]

 2+a = [3 4 5]



Para isso funcionar, o que o NumPy faz por trás dos panos é uma técnica chamada **broadcasting**. 

Ele transforma o escalar 2 num vetor de mesmas dimensões do vetor "a" e realiza as operações de soma e multiplicação para cada elemento desses vetores. Clarificando:


*   2 x a -> [2,2,2] x [1,2,3] -> [2x1, 2x2, 2x3] -> [2, 4, 6]
*   2 + a -> [2,2,2] + [1,2,3] -> [2+1, 2+2, 2+3] -> [3, 4, 5]



# **Trabalhando com vetores (arrays 1D) no NumPy**

# **Inicialização de vetores**

**Inicialização básica**

In [ ]:
a = np.array([1., 2., 3.])
print(f"Array: {a}")
print(f"Tipo do Array: {a.dtype}")
print(f"Tamanho do Array: {a.shape}")

Array: [1. 2. 3.]
Tipo do Array: float64
Tamanho do Array: (3,)


**Inicializando o array definindo seu tipo explicitamente**

In [ ]:
a = np.array([1., 2., 3.], dtype=np.uint8)
print(f"Array: {a}")
print(f"Tipo do Array: {a.dtype}")
print(f"Tamanho do Array: {a.shape}")

Array: [1 2 3]
Tipo do Array: uint8
Tamanho do Array: (3,)


**Inicializando o array com todos os elementos tendo um mesmo valor arbitrário**

In [ ]:
setes = np.full(3, 7)
print(f"Array: {setes}")
print(f"Tipo do Array: {setes.dtype}")
print(f"Tamanho do Array: {setes.shape}")

Array: [7 7 7]
Tipo do Array: int64
Tamanho do Array: (3,)


**Inicializando o array com um range de valores - np.arange (adequado apenas para valores inteiros)**

In [ ]:
range1 = np.arange(6) # stop
print(f"Range 1: {range1}")
print()

range2 = np.arange(1, 5) # start, stop
print(f"Range 2: {range2}")
print()

range3 = np.arange(0, 10, 2) # start, stop, step
print(f"Range 3: {range3}")
print()

range4 = np.arange(0.1, 0.3, 0.1)
print(f"Range 4: {range4}")
print()

# Quando utilizamos o arange para floats, podemos nos deparar com comportamentos anômalos.
# Nesse caso, não era para o 0.8 estar no vetor, pois o intervalo é aberto. Mas ainda assim ele aparece 
range_erro = np.arange(0.5, 0.8, 0.1)
print(f"Range anômalo em floats: {range_erro}")

Range 1: [0 1 2 3 4 5]

Range 2: [1 2 3 4]

Range 3: [0 2 4 6 8]

Range 4: [0.1 0.2]

Range anômalo em floats: [0.5 0.6 0.7 0.8]


**Inicializando o array com um range de valores - np.linspace**

In [ ]:
linspace1 = np.linspace(0.1, 0.5, 5)
print(f"Linspace 1: {linspace1}")
print()

linspace2 = np.linspace(2.5, 3.5, 3)
print(f"Linspace 2: {linspace2}")
print()

Linspace 1: [0.1 0.2 0.3 0.4 0.5]

Linspace 2: [2.5 3.  3.5]



**Inicializando o array com valores aleatórios**



In [ ]:
random_int = np.random.randint(0, 10, 3)
print(f"Inteiros randômicos: {random_int}")
print()

random_float = np.random.uniform(1.5, 4.5, 4)
print(f"Floats randômicos: {random_float}")

Inteiros randômicos: [2 1 5]

Floats randômicos: [3.46938826 3.51174433 1.85700481 2.46291218]


# **Indexação de vetores**

**Funcionam todas as formas que fazíamos com listas...**

In [ ]:
a = np.arange(1,10)
print(f"a = {a}")
print()

print("Indexações tradicionais: ")
print(f"a[1] = {a[1]}")
print(f"a[2:4] = {a[2:4]}")
print(f"a[-2:] = {a[-2:]}")
print(f"a[::2] = {a[::2]}")

a = [1 2 3 4 5 6 7 8 9]

Indexações tradicionais: 
a[1] = 2
a[2:4] = [3 4]
a[-2:] = [8 9]
a[::2] = [1 3 5 7 9]


In [ ]:
a = np.arange(1,10)
b = a[2:4]
c = a[[7,8]]
print(f"a = {a}")
print(f"b = {b}")
print(f"c = {c}")

a = [1 2 3 4 5 6 7 8 9]
b = [3 4]
c = [8 9]


In [ ]:
b[0] = 42
c[1] = 84
print(f"a = {a}")
print(f"b = {b}")
print(f"c = {c}")

a = [ 1  2 42  4  5  6  7  8  9]
b = [42  4]
c = [ 8 84]


**E mais!**

**Fancy Indexing**

In [ ]:
a = np.arange(1,10)
print(f"a = {a}")
print()

print("Selecionando os valores dos índices 1, 3 e 4:")
print(f"a[[1, 3, 4]] = {a[[1,3,4]]}")

a = [1 2 3 4 5 6 7 8 9]

Selecionando os valores dos índices 1, 3 e 4:
a[[1, 3, 4]] = [2 4 5]


**Indexação booleana**

A indexação booleana transforma todos os elementos de um array em booleanos de acordo com uma operação lógica

In [ ]:
a = np.arange(1,10)
print(f"a = {a}")
print()

print(f"a>5 = {a>5}")
print()
print(f"a>=3 & a <=5 = {(a>=3) & (a<=5)}")
print()
print(f"a<3 | a>5 = {(a<3) | (a>5)}")

a = [1 2 3 4 5 6 7 8 9]

a>5 = [False False False False False  True  True  True  True]

a>=3 & a <=5 = [False False  True  True  True False False False False]

a<3 | a>5 = [ True  True False False False  True  True  True  True]


**Aplicações da indexação booleana**

In [ ]:
a = np.arange(1,10)
print(f"a = {a}")
print()

print("Existe algum elemento maior que 5 no vetor?")
print(f"Método np.any(): {np.any(a>5)}")
print()
print("Todos os elementos do vetor são maiores que 5?")
print(f"Método np.all(): {np.all(a>5)}")
print()
print("Selecionando os valores maiores que 5:")
print(f"a[a>5] = {a[a>5]}")
print()
print("Selecionando os valores no intervalo [3,5]: ")
print(f"a[(a>=3) & (a<=5)] = {a[(a>=3) & (a<=5)]}")
print()
print("Selecionando os valores menores que 3 e maiores que 5: ")
print(f"a[(a<3) | (a>5)] = {a[(a<3) | (a>5)]}")

a = [1 2 3 4 5 6 7 8 9]

Existe algum elemento maior que 5 no vetor?
Método np.any(): True

Todos os elementos do vetor são maiores que 5?
Método np.all(): False

Selecionando os valores maiores que 5:
a[a>5] = [6 7 8 9]

Selecionando os valores no intervalo [3,5]: 
a[(a>=3) & (a<=5)] = [3 4 5]

Selecionando os valores menores que 3 e maiores que 5: 
a[(a<3) | (a>5)] = [1 2 6 7 8 9]


# **Operações com vetores**

Como vimos na seção de vetorização, o NumPy realiza as operações entre vetores de elemento por elemento. Por conta disso, faz-se necessário que os dois vetores tenham um mesmo tamanho (shape). 

Quando temos um escalar e um vetor, é aplicada uma técnica chamada **broadcasting** para transformar o escalar em um outro vetor de mesmo tamanho.

Uma descrição geral das operações no NumPy é:

> Sejam dois vetores A = [a1, a2] e B = [b1, b2]. Vamos simular os resultados de diferentes operações entre A e B:
>
> * A + B = [a1 + b1, a2 + b2]
> * A - B = [a1 - b1, a2 - b2]
> * A x B = [a1 x b1, a2 x b2]
> * A / B = [a1 / b1, a2 / b2]








**Vamos utilizar as seguintes variáveis como exemplo:**

In [ ]:
a = np.array([1,2])
b = np.array([4,8])
c = np.array([3,6,9])
d = np.array([5,10,15])
e = 5

print(f"a = {a}")
print(f"b = {b}")
print(f"c = {c}")
print(f"d = {d}")
print(f"e = {e}")

a = [1 2]
b = [4 8]
c = [3 6 9]
d = [ 5 10 15]
e = 5


**Podemos aplicar as seguintes e várias outras operações:**

In [ ]:
print(f"a + b = {a+b}")
print(f"d - c = {d-c}")
print(f"a * e = {a*e}") # Broadcasting! e passa a ser [5,5]
print(f"d / e = {d/e}") # Broadcasting! e passa a ser [5,5,5]

#print(f"b + c = {b+c}") # Erro! b e c não podem ser convertidos para o mesmo tamanho

a + b = [ 5 10]
d - c = [2 4 6]
a * e = [ 5 10]
d / e = [1. 2. 3.]


# **Inserção e remoção de elementos num vetor**

**Método append**

Insere elemento(s) no fim do vetor

In [ ]:
a = np.array([1,2,3])
print(f"a = {a}")

a = np.append(a, 4)
print(f"a = {a}")

a = np.append(a, [5,6,7,8])
print(f"a = {a}")

a = [1 2 3]
a = [1 2 3 4]
a = [1 2 3 4 5 6 7 8]


**Método insert**

Adiciona um elemento num determinado índice do array

In [ ]:
a = np.array([2,4,16])
print(f"a = {a}")

a = np.insert(a, 2, 6)
print(f"a = {a}")

# insere sequencialmente os elementos de [8,12,14] A PARTIR do índice 3.
# Ou seja, o 8 é inserido no índice 3, o 12 no índice 4 e o 14 no índice 5.
a = np.insert(a, 3, [8,12,14])
print(f"a = {a}")

# insere primeiro o 10 no índice 4, depois o 0 no índice 0
a = np.insert(a, [4,0], [10,0])
print(f"a = {a}")

a = [ 2  4 16]
a = [ 2  4  6 16]
a = [ 2  4  6  8 12 14 16]
a = [ 0  2  4  6  8 10 12 14 16]


**Método delete**

Remove o elemento de um determinado índice do array

In [ ]:
a = np.array([5,4,3,2,1,2,3,4,5])
print(f"a = {a}")

a = np.delete(a,1)
print(f"a = {a}")

# Remove os elementos de índice 0,1,5,6,7
a = np.delete(a, [0,1,5,6,7])
print(f"a = {a}")

a = [5 4 3 2 1 2 3 4 5]
a = [5 3 2 1 2 3 4 5]
a = [2 1 2]


# **Ordenação de vetores**

**Método sort**

In [ ]:
a = np.array([5,1,4,6,2,3])
print(f"a = {a}")
a.sort()
print(f"a ordenado = {a}")

a = [5 1 4 6 2 3]
a ordenado = [1 2 3 4 5 6]


**Artimanha para ordenação de forma decrescente**

In [ ]:
a = np.array([5,1,4,6,2,3])
print(f"a = {a}")
a.sort()
print(f"a ordenado = {a}")
a = a[::-1]
print(f"a decrescente = {a}")

a = [5 1 4 6 2 3]
a ordenado = [1 2 3 4 5 6]
a decrescente = [6 5 4 3 2 1]


# **Funções estatísticas para vetores**

In [ ]:
a = np.array([1,2,3])
print(f"a =  {a}")
print()

print(f"Maior elemento do vetor: {np.max(a)}")
print(f"Menor elemento do vetor: {np.min(a)}")
print(f"Soma dos elementos do vetor: {np.sum(a)}")
print(f"Média dos elementos do vetor: {np.mean(a)}")

a =  [1 2 3]

Maior elemento do vetor: 3
Menor elemento do vetor: 1
Soma dos elementos do vetor: 6
Média dos elementos do vetor: 2.0


# **Cópia de vetores**

**Método view**

Quando criamos o array v a partir da aplicação do método view ao array l, v e l se referem a um mesmo array, apenas com apelidos diferentes. Dessa forma, quando alteramos algum desses arrays, também estamos alterando o outro.

In [ ]:
l = np.array([1,2,3])
v = l.view()

print(f"v = {v}")
print(f"l = {l}")
print()

v[0] = 42
print(f"v = {v}")
print(f"l = {l}")

v = [1 2 3]
l = [1 2 3]

v = [42  2  3]
l = [42  2  3]


**Método copy**

Quando criamos o array v a partir da aplicação do método copy ao array l, v e l são arrays distintos na memória. A alteração de um desses arrays não se reflete no outro.

In [ ]:
l = np.array([1,2,3])
v = l.copy()

print(f"v = {v}")
print(f"l = {l}")
print()

v[0] = 42
print(f"v = {v}")
print(f"l = {l}")

v = [1 2 3]
l = [1 2 3]

v = [42  2  3]
l = [1 2 3]


# **Trabalhando com matrizes (arrays 2D) no NumPy**

# **Inicialização de matrizes**

Assim como em listas, uma matriz também pode ser compreendida como um array de arrays em Python e sua inicialização funciona da mesma forma que os vetores. 

Teremos uma diferença no shape do array agora, que será uma tupla de dois valores. O primeiro representa as linhas e o segundo as colunas.

No caso a seguir, temos uma matriz de 2 linhas e 3 colunas

In [ ]:
a = np.array([[1, 2, 3], 
             [4, 5, 6]])
print(a)
print(f"Tipo do Array: {a.dtype}")
print(f"Tamanho do Array: {a.shape}")

[[1 2 3]
 [4 5 6]]
Tipo do Array: int64
Tamanho do Array: (2, 3)


Podemos também utilizar todos os métodos de inicialização que vimos com os vetores. Agora, passamos a nossa tupla de dois valores como parâmetro para termos o shape do array.

Vamos ver um exemplo para o método **randint** (inicializa a matriz com inteiros randômicos).

In [ ]:
# inteiros aleatorios de 0 a 20 numa matriz de 5 linhas por 4 colunas
random_int = np.random.randint(0, 20, (5,4))
print(random_int)
print()
print(f"Tamanho da matriz: {random_int.shape}")

[[ 7 11 17 12]
 [17 18 13  3]
 [19  2  4 10]
 [ 9  7  9 18]
 [17 18  8  7]]

Tamanho da matriz: (5, 4)


# **Indexação de matrizes**

Para acessarmos um índice ij de uma matriz a, basta utilizarmos a[i,j].

In [ ]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(a)
print()

print(f"a[1,2] = {a[1,2]}")

[[1 2 3]
 [4 5 6]
 [7 8 9]]

a[1,2] = 6


As demais formas de indexação também funcionam. Vamos ver alguns exemplos de slicing e fancy index:

In [ ]:
a = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])
print(a)
print()

print(f"a[1,:] = {a[1,:]}") # retorna todos os elementos da linha 1
print(f"a[:,2] = {a[:,2]}") # retorna todos os elementos da coluna 2
print(f"a[-1,[1,2]] = {a[-1,[1,2]]}") # retorna os últimos elementos das colunas 1 e 2

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

a[1,:] = [5 6 7 8]
a[:,2] = [ 3  7 11]
a[-1,[1,2]] = [10 11]


# **Operações e manipulação de matrizes**

Operações aritméticas também são feitas de elemento para elemento e também temos o broadcasting.

In [ ]:
a = np.array([[1,2], [3,4]])
b = np.array([[2,0], [0,2]])
c = 5

print(f"a = \n{a}")
print(f"b = \n{b}")
print(f"c = {c}")
print()

print(f"a*b = \n{a*b}")
print(f"a+c = \n{a+c}") # Broadcasting! c passa a ser [[5,5], [5,5]]

a = 
[[1 2]
 [3 4]]
b = 
[[2 0]
 [0 2]]
c = 5

a*b = 
[[2 0]
 [0 8]]
a+c = 
[[6 7]
 [8 9]]


**Operador @: Multiplicação de matrizes**

In [ ]:
a = np.array(([[1,2,3]]))
b = np.array(([[1],[2],[3]]))
print(f"a = {a}")
print(f"Dimensões de a: {a.shape}")
print(f"b = \n{b}")
print(f"Dimensões de b: {b.shape}")
print()

print(f"a@b = {a@b}")
print()
print(f"b@a = \n{b@a}")

a = [[1 2 3]]
Dimensões de a: (1, 3)
b = 
[[1]
 [2]
 [3]]
Dimensões de b: (3, 1)

a@b = [[14]]

b@a = 
[[1 2 3]
 [2 4 6]
 [3 6 9]]


**Transposição de matrizes**

A transposição de uma matriz A pode ser feita por meio de: A.T 

In [ ]:
a = np.array(([[1,2,3]])) # obs! Se fizéssemos com um vetor (shape (3,), não funcionaria)
print(f"a = {a}")
print(f"Dimensões de a: {a.shape}")
print()
print(f"a transposta = \n{a.T}")
print(f"Dimensões de a.T: {a.T.shape}")

a = [[1 2 3]]
Dimensões de a: (1, 3)

a transposta = 
[[1]
 [2]
 [3]]
Dimensões de a.T: (3, 1)


**Método Reshape**

Dado um vetor ou uma matriz com x elementos, podemos mudar as dimensões dela para qualquer outra matriz com a mesma quantidade x de elementos

In [ ]:
a = np.arange(1,7)
print(f"a = {a}")
print(f"Dimensões de a = {a.shape}")
print()

a = a.reshape(2,3) # transforma numa matriz de 2 linhas e 3 colunas
print(f"a = \n{a}")
print(f"Dimensões de a = {a.shape}")

a = [1 2 3 4 5 6]
Dimensões de a = (6,)

a = 
[[1 2 3]
 [4 5 6]]
Dimensões de a = (2, 3)


# **Ampliando as operações com matrizes por meio do parâmetro axis**

Em várias operações que envolvem matrizes, você pode querer especificar se essas operações ocorrem somente nas linhas ou somente nas colunas das matrizes. Isso é feito por meio do parâmetro axis.

*   axis = 0 denota que, para cada coluna, opere sobre todos os elementos nessa coluna
*   axis = 1 denota que, para cada linha, opere sobre todos os elementos nessa linha
* axis = None denota que a operação será feita sobre todos os elementos da matriz

**Método sum utilizando o parâmetro axis**

In [ ]:
a = np.array([[1,2,3], [4,5,6]])
print(f"a = \n{a}")
print()

# axis = None pode ser omitido
print(f"Soma de todos os elementos da matriz: {np.sum(a)}")
# como temos 3 colunas, retorna um array de shape (3,),
# sendo a[0] o somatório da coluna 0, a[1] o somatório da coluna 1
# e a[2] o somatório da coluna 2
print(f"Soma de todos os elementos de cada coluna da matriz: {np.sum(a, axis=0)}")
# como temos 2 linhas, retorna um array de shape (2,),
# sendo a[0] o somatório da linha 0 e a[1] o somatório da linha 1
print(f"Soma de todos os elementos de cada linha da matriz: {np.sum(a, axis=1)}") 

a = 
[[1 2 3]
 [4 5 6]]

Soma de todos os elementos da matriz: 21
Soma de todos os elementos de cada coluna da matriz: [5 7 9]
Soma de todos os elementos de cada linha da matriz: [ 6 15]


**Inserção em matrizes**

Dado um array com shape (x,y), podemos utilizar o método append para:

* Inserir um outro array com shape (m,y) abaixo dele, utilizando axis=0. Estamos inserindo m linhas para cada coluna do array original.

* Inserir um outro array com shape (x,n) à sua direita, utilizando axis=1. Estamos inserindo n colunas para cada linha do array original.

Caso necessitemos de utilizar o método insert, a lógica é a mesma. A diferença é que:

* Não estamos mais inserindo linhas necessariamente abaixo, e sim numa posição específica
* Não estamos mais inserindo colunas necessariamente à direita, e sim numa posição específica

In [ ]:
a = np.arange(1,16)
a = a.reshape(3,5)
print(f"a = \n{a}")
print(f"Dimensões de a: {a.shape}")
print()

a_insert = np.insert(a, 1, np.full((1,5), 7), axis=0)
print(f"Inserindo uma linha de 7s entre a primeira e a segunda coluna de A = \n{a_insert}")
print(f"Dimensões de a: {a_insert.shape}")
print()

a_append = np.append(a, np.full((3,2), 0), axis=1)
print(f"Inserindo 2 colunas de 0s à direita de A = \n{a_append}")
print(f"Dimensões de a: {a_append.shape}")
print()

a = 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
Dimensões de a: (3, 5)

Inserindo uma linha de 7s entre a primeira e a segunda coluna de A = 
[[ 1  2  3  4  5]
 [ 7  7  7  7  7]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
Dimensões de a: (4, 5)

Inserindo 2 colunas de 0s à direita de A = 
[[ 1  2  3  4  5  0  0]
 [ 6  7  8  9 10  0  0]
 [11 12 13 14 15  0  0]]
Dimensões de a: (3, 7)



**Remoção de linhas ou colunas em matrizes**

Utilizamos o método delete para:

* Remover uma determinada linha utilizando o parâmetro axis = 0 
* Remover uma determinada coluna utilizando o parâmetro axis = 1



In [ ]:
a = np.arange(1,16)
a = a.reshape(3,5)
print(f"a = \n{a}")
print(f"Dimensões de a: {a.shape}")
print()

a_delete1 = np.delete(a, 1, axis=0)
print(f"Removendo a linha 1 = \n{a_delete1}")
print(f"Dimensões de a: {a_delete1.shape}")
print()

a_delete13 = np.delete(a, [1,3], axis=1)
print(f"Removendo as colunas 1 e 3 = \n{a_delete13}")
print(f"Dimensões de a: {a_delete13.shape}")
print()

a = 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
Dimensões de a: (3, 5)

Removendo a linha 1 = 
[[ 1  2  3  4  5]
 [11 12 13 14 15]]
Dimensões de a: (2, 5)

Removendo as colunas 1 e 3 = 
[[ 1  3  5]
 [ 6  8 10]
 [11 13 15]]
Dimensões de a: (3, 3)

